version = 2

[build]
builder = "nixpacks"
buildCommand = "apt-get update && apt-get install -y ffmpeg"

[deploy]
startCommand = "node index.js"
healthcheckPath = "/"
healthcheckTimeout = 100

[phases.setup]
nixPkgs = ["ffmpeg"]
