# Railway Deployment Configuration

# Node.js version
NODE_VERSION=20

# Command to run the bot
CMD="node index.js"

# Install Python and yt-dlp before running the app
NIXPACKS_PKGS="python3 python3-pip ffmpeg"
BUILD_COMMAND="pip install yt-dlp && mkdir -p temp"
