# Railway Deployment Configuration

# Node.js version
NODE_VERSION=20

# Command to run the bot
CMD="node index.js"

# Create temp directory for yt-dlp downloads
PRE_BUILD="mkdir -p temp"

# Install yt-dlp if not already installed
PRE_DEPLOY="pip install yt-dlp"
